### ISSUE TITLE
是否有考虑优化下 UI?

### ISSUE THREAD

**Issue by langyo** [yuezhuxue/mite#1]
虽然这里的作品其实挺棒的都，但展示页却仿佛来自上个世纪网页三剑客的时代……

如果你有想让界面改好看点的意愿，我可以帮你把界面拿 React + Material-UI 升级下的~甚至可能视情况加入评论功能（不过这就基本相当于个人博客了

静待你的回复~

**Comment by yuezhuxue** [comment]
暂时不考虑，不过还是谢谢你
如果以后遇到相关问题，还望不吝赐教
